dependencies:
  - name: mongodb
    version: 0.4.9
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: redis
    version: 0.8.0
    repository: https://kubernetes-charts.storage.googleapis.com