# Default values for scalarm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: scalarm/experiment-manager
  tag: 1.0.1
  pullPolicy: IfNotPresent
service:
  name: scalarm-svc
  type: ClusterIP
  externalPort: 3000	
  internalPort: 3000
env:
  expm_port: 3000
  rails_env: production
  secret_key_base: alamakota
  inf_svc_url: localhost:3000/information
  inf_svc_login: scalarm
  inf_svc_pass: scalarm1024
  skq_login: scalarm
  skq_pass: scalarm1024
  redis_host: redis
  redis_port: 6379
  mongo_host: mongodb
  mongo_port: 27017
  mongodb_name: mongodb
resources:

mongodb:
  persistence:
    enabled: false

redis:
  usePassword: false
  persistence: 
    enabled: false
  