# Default values for scalarm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: scalarm/experiment-manager
  tag: 1.0.2
  pullPolicy: IfNotPresent
service:
  name: scalarm-svc
  type: NodePort
  externalPort: 3000	
  internalPort: 3000
env:
  expm_port: 3000
  # rails environment(production/development/test and so on)that Rails will run under
  rails_env: production
  secret_key_base: alamakota
  # information service url - for example: kubectl exec -it scalarm_pod_name bash -> curl -k https://localhost:3000/information/experiment_managers
  inf_svc_url: localhost:3000/information
  inf_svc_login: scalarm
  inf_svc_pass: scalarm1024
  # sidekiq login and password (https://github.com/mperham/sidekiq)
  skq_login: scalarm
  skq_pass: scalarm1024
  redis_host: redis
  redis_port: 6379
  mongo_host: mongodb
  mongo_port: 27017
  mongodb_name: mongodb
  #login and password for scalarm user
  user_login: scalarm
  user_pass: scalarm
resources:


redis:
  usePassword: false
  